apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-app
data:
  NODE_ENV: "production"
  PORT: "3000"

  ALLOWED_ORIGINS: "http://a3e7216594beb4c97a81f21e535ad95f-1290048814.us-east-1.elb.amazonaws.com"

  JWT_EXPIRES_IN: "15m"
  BCRYPT_ROUNDS: "12"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
